
// Generated by Cadence Genus(TM) Synthesis Solution 16.23-s049_1
// Generated on: Jul  6 2026 14:58:45 IST (Jul  6 2026 09:28:45 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  DFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .Q
       (count[7]));
  DFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .Q
       (count[6]));
  XNOR2X1 g129__7837(.A (n_11), .B (count[7]), .Y (n_13));
  XNOR2X1 g131__7557(.A (n_10), .B (count[6]), .Y (n_12));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_9), .Q
       (count[5]));
  NAND2BXL g133__7654(.AN (n_10), .B (count[6]), .Y (n_11));
  XNOR2X1 g134__8867(.A (n_8), .B (count[5]), .Y (n_9));
  DFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_7), .Q
       (count[4]));
  NAND2BXL g136__1377(.AN (n_8), .B (count[5]), .Y (n_10));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_5), .Q
       (count[3]));
  XNOR2X1 g137__3717(.A (n_6), .B (count[4]), .Y (n_7));
  NAND2BXL g139__4599(.AN (n_6), .B (count[4]), .Y (n_8));
  XNOR2X1 g140__3779(.A (n_4), .B (count[3]), .Y (n_5));
  DFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_3), .Q
       (count[2]));
  NAND2BXL g142__2007(.AN (n_4), .B (count[3]), .Y (n_6));
  XNOR2X1 g143__1237(.A (n_2), .B (count[2]), .Y (n_3));
  DFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_1), .Q
       (count[1]));
  NAND2BXL g145__1297(.AN (n_2), .B (count[2]), .Y (n_4));
  CLKXOR2X1 g146__2006(.A (count[0]), .B (count[1]), .Y (n_1));
  NAND2XL g148__2833(.A (count[1]), .B (count[0]), .Y (n_2));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule
