
// Generated by Cadence Genus(TM) Synthesis Solution 16.23-s049_1
// Generated on: Aug 19 2026 14:34:15 IST (Aug 19 2026 09:04:15 UTC)

// Verification Directory fv/count 

module count(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20;
  DFFQXL \count_reg[7] (.CK (clk), .D (n_20), .Q (count[7]));
  NOR2X1 g129__7837(.A (rst), .B (n_19), .Y (n_20));
  DFFQXL \count_reg[6] (.CK (clk), .D (n_18), .Q (count[6]));
  XNOR2X1 g131__7557(.A (count[7]), .B (n_15), .Y (n_19));
  NOR2X1 g132__7654(.A (rst), .B (n_17), .Y (n_18));
  DFFQXL \count_reg[5] (.CK (clk), .D (n_16), .Q (count[5]));
  XNOR2X1 g134__8867(.A (count[6]), .B (n_14), .Y (n_17));
  NOR2X1 g136__1377(.A (rst), .B (n_13), .Y (n_16));
  DFFQXL \count_reg[4] (.CK (clk), .D (n_12), .Q (count[4]));
  AND2XL g135__3717(.A (count[6]), .B (n_14), .Y (n_15));
  XNOR2X1 g138__4599(.A (count[5]), .B (n_11), .Y (n_13));
  NOR2X1 g140__3779(.A (rst), .B (n_10), .Y (n_12));
  DFFQXL \count_reg[3] (.CK (clk), .D (n_9), .Q (count[3]));
  AND2XL g139__2007(.A (count[5]), .B (n_11), .Y (n_14));
  DFFQXL \count_reg[2] (.CK (clk), .D (n_7), .Q (count[2]));
  XNOR2X1 g142__1237(.A (count[4]), .B (n_8), .Y (n_10));
  NOR2X1 g144__1297(.A (rst), .B (n_6), .Y (n_9));
  AND2XL g143__2006(.A (count[4]), .B (n_8), .Y (n_11));
  NOR2X1 g148__2833(.A (rst), .B (n_4), .Y (n_7));
  XNOR2X1 g146__7547(.A (count[3]), .B (n_5), .Y (n_6));
  DFFQXL \count_reg[1] (.CK (clk), .D (n_3), .Q (count[1]));
  AND2XL g147__7765(.A (count[3]), .B (n_5), .Y (n_8));
  XNOR2X1 g150__9867(.A (count[2]), .B (n_2), .Y (n_4));
  NOR2X1 g152__3377(.A (rst), .B (n_1), .Y (n_3));
  DFFHQX1 \count_reg[0] (.CK (clk), .D (n_0), .Q (count[0]));
  AND2XL g151__9719(.A (count[2]), .B (n_2), .Y (n_5));
  XNOR2X1 g154__1591(.A (count[1]), .B (count[0]), .Y (n_1));
  NOR2X1 g155__6789(.A (rst), .B (count[0]), .Y (n_0));
  AND2XL g156__5927(.A (count[1]), .B (count[0]), .Y (n_2));
endmodule
