/* Generated by Tessent Shell 2022.4 at Fri Aug 21 13:43:57 IST 2026 */

`timescale 1ns / 1ns

module counter(clk, rst, count, ts_si, ts_so, scan_en);
  input  [0:0] ts_si;
  input  clk, rst, scan_en;
  output [7:0] count;
  output [0:0] ts_so;

  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12, 
       n_13, ts_lockup_latchn_clkc1_intno7_, ts_pbuf_extsi8_;

  assign ts_so = ts_lockup_latchn_clkc1_intno7_;
  SDFFRHQX1 \count_reg[7] (
      .Q(count[7]), .D(n_13), .SE(scan_en), .SI(ts_pbuf_extsi8_), .RN(rst), .CK(clk)
  );
  SDFFRHQX1 \count_reg[6] (
      .Q(count[6]), .D(n_12), .SE(scan_en), .SI(count[7]), .RN(rst), .CK(clk)
  );
  XNOR2X1 g129__7837(
      .Y(n_13), .A(n_11), .B(count[7])
  );
  XNOR2X1 g131__7557(
      .Y(n_12), .A(n_10), .B(count[6])
  );
  SDFFRHQX1 \count_reg[5] (
      .Q(count[5]), .D(n_9), .SE(scan_en), .SI(count[6]), .RN(rst), .CK(clk)
  );
  NAND2BXL g133__7654(
      .Y(n_11), .AN(n_10), .B(count[6])
  );
  XNOR2X1 g134__8867(
      .Y(n_9), .A(n_8), .B(count[5])
  );
  SDFFRHQX1 \count_reg[4] (
      .Q(count[4]), .D(n_7), .SE(scan_en), .SI(count[5]), .RN(rst), .CK(clk)
  );
  NAND2BXL g136__1377(
      .Y(n_10), .AN(n_8), .B(count[5])
  );
  SDFFRHQX1 \count_reg[3] (
      .Q(count[3]), .D(n_5), .SE(scan_en), .SI(count[4]), .RN(rst), .CK(clk)
  );
  XNOR2X1 g137__3717(
      .Y(n_7), .A(n_6), .B(count[4])
  );
  NAND2BXL g139__4599(
      .Y(n_8), .AN(n_6), .B(count[4])
  );
  XNOR2X1 g140__3779(
      .Y(n_5), .A(n_4), .B(count[3])
  );
  SDFFRHQX1 \count_reg[2] (
      .Q(count[2]), .D(n_3), .SE(scan_en), .SI(count[3]), .RN(rst), .CK(clk)
  );
  NAND2BXL g142__2007(
      .Y(n_6), .AN(n_4), .B(count[3])
  );
  XNOR2X1 g143__1237(
      .Y(n_3), .A(n_2), .B(count[2])
  );
  SDFFRHQX1 \count_reg[1] (
      .Q(count[1]), .D(n_1), .SE(scan_en), .SI(count[2]), .RN(rst), .CK(clk)
  );
  NAND2BXL g145__1297(
      .Y(n_4), .AN(n_2), .B(count[2])
  );
  CLKXOR2X1 g146__2006(
      .Y(n_1), .A(count[0]), .B(count[1])
  );
  NAND2XL g148__2833(
      .Y(n_2), .A(count[1]), .B(count[0])
  );
  SDFFRX1 \count_reg[0] (
      .Q(count[0]), .QN(n_0), .D(n_0), .SE(scan_en), .SI(count[1]), .RN(rst), .CK(clk)
  );
  TLATNXL ts_lockup_latchn_clkc1_intno7_i(
      .Q(ts_lockup_latchn_clkc1_intno7_), .QN(), .D(count[0]), .GN(clk)
  );
  DLY4X4 tessent_persistent_cell_buf_extsi8_i(
      .Y(ts_pbuf_extsi8_), .A(ts_si)
  );
endmodule
