/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID mjlab1.mjcollege.ac.in)
#  Generated on:      Wed Aug 19 14:17:50 2026
#  Design:            counter
#  Command:           saveNetlist ./count_final.v -phys -includePowerGround -excludeLeafCell
###############################################################
*/
/* Generated by Tessent Shell 2022.4 at Wed Aug 19 13:03:55 IST 2026 */
module counter (
	clk, 
	rst, 
	count, 
	SI_0, 
	SO_0, 
	scan_en, 
	VDD, 
	VSS);
   input clk;
   input rst;
   output [7:0] count;
   input SI_0;
   output SO_0;
   input scan_en;
   inout VDD;
   inout VSS;
   supply1 VDD;
   supply0 VSS;

   // Internal wires
   wire FE_PHN0_scan_en;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire ts_lockup_latchn_clkc1_intno7_;
   wire ts_pbuf_extsi8_;

   assign SO_0 = ts_lockup_latchn_clkc1_intno7_ ;

   // Module instantiations
   CLKBUFX2 FE_PHC0_scan_en (
	.Y(FE_PHN0_scan_en),
	.A(scan_en), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[7]  (
	.Q(count[7]),
	.D(n_13),
	.SE(FE_PHN0_scan_en),
	.SI(count[6]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[6]  (
	.Q(count[6]),
	.D(n_12),
	.SE(FE_PHN0_scan_en),
	.SI(ts_pbuf_extsi8_),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g129__7837 (
	.Y(n_13),
	.A(n_11),
	.B(count[7]), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g131__7557 (
	.Y(n_12),
	.A(n_10),
	.B(count[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[5]  (
	.Q(count[5]),
	.D(n_9),
	.SE(FE_PHN0_scan_en),
	.SI(count[3]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXL g133__7654 (
	.Y(n_11),
	.AN(n_10),
	.B(count[6]), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g134__8867 (
	.Y(n_9),
	.A(n_8),
	.B(count[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[4]  (
	.Q(count[4]),
	.D(n_7),
	.SE(FE_PHN0_scan_en),
	.SI(count[1]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXL g136__1377 (
	.Y(n_10),
	.AN(n_8),
	.B(count[5]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[3]  (
	.Q(count[3]),
	.D(n_5),
	.SE(FE_PHN0_scan_en),
	.SI(count[4]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g137__3717 (
	.Y(n_7),
	.A(n_6),
	.B(count[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXL g139__4599 (
	.Y(n_8),
	.AN(n_6),
	.B(count[4]), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g140__3779 (
	.Y(n_5),
	.A(n_4),
	.B(count[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[2]  (
	.Q(count[2]),
	.D(n_3),
	.SE(FE_PHN0_scan_en),
	.SI(count[7]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXL g142__2007 (
	.Y(n_6),
	.AN(n_4),
	.B(count[3]), 
	.VSS(VSS), 
	.VDD(VDD));
   XNOR2X1 g143__1237 (
	.Y(n_3),
	.A(n_2),
	.B(count[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRHQX1 \count_reg[1]  (
	.Q(count[1]),
	.D(n_1),
	.SE(FE_PHN0_scan_en),
	.SI(count[2]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2BXL g145__1297 (
	.Y(n_4),
	.AN(n_2),
	.B(count[2]), 
	.VSS(VSS), 
	.VDD(VDD));
   CLKXOR2X1 g146__2006 (
	.Y(n_1),
	.A(count[0]),
	.B(count[1]), 
	.VSS(VSS), 
	.VDD(VDD));
   NAND2XL g148__2833 (
	.Y(n_2),
	.A(count[1]),
	.B(count[0]), 
	.VSS(VSS), 
	.VDD(VDD));
   SDFFRX1 \count_reg[0]  (
	.Q(count[0]),
	.QN(n_0),
	.D(n_0),
	.SE(FE_PHN0_scan_en),
	.SI(count[5]),
	.RN(rst),
	.CK(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   TLATNXL ts_lockup_latchn_clkc1_intno7_i (
	.Q(ts_lockup_latchn_clkc1_intno7_),
	.QN(),
	.D(count[0]),
	.GN(clk), 
	.VSS(VSS), 
	.VDD(VDD));
   DLY4X4 tessent_persistent_cell_buf_extsi8_i (
	.Y(ts_pbuf_extsi8_),
	.A(SI_0), 
	.VSS(VSS), 
	.VDD(VDD));

   // Fillers and physical instances.
   FILL1 ENDCAP_12 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_11 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_10 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_9 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_8 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_7 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_6 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_5 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_4 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_3 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_2 (
	.VDD(VDD), 
	.VSS(VSS) );
   FILL1 ENDCAP_1 (
	.VDD(VDD), 
	.VSS(VSS) );
endmodule

